### ISSUE TITLE
hr-HR

### ISSUE THREAD

**Issue by JFerzHack** [PoGo-Devs/pogo-devs.github.io#11]
@PoGo-Devs/translators 

Croatia Translation
## Tasks
- [x] about
- [x] contribute
- [x] footer
- [x] instructions
- [x] template

ref issue #3

**Comment by dxdydado** [comment]
need file or write here?

about = O
contribute = doprinijeti
footer = podnožje  
instructions = upute
template = predložak

**Comment by JFerzHack** [comment]
I uploaded files to  Locales> hr-HR.
I just translated about, and I'l start translating instructions now

**Comment by JFerzHack** [comment]
@dxdydado and you do not need to translate 
instructions = upute
template = predložak

**Comment by JFerzHack** [comment]
everything is done

**Comment by josecfreittas** [comment]
Great, thanks. The language was added to the site footer.
