### ISSUE TITLE
Translation FR

### ISSUE THREAD

**Issue by DarkAngelFR-zz** [PoGo-Devs/pogo-devs.github.io#4]
@PoGo-Devs/translators

I will start FR translation ^^
ETA : tomorrow 9h french time

Ref Issue #3 
- [x] about
- [x] contribute
- [x] footer
- [x] instuctions
- [x] template

**Comment by Synochy** [comment]
If you need help tell me ;)

**Comment by DarkAngelFR-zz** [comment]
I just commit fr-FR

already done : 
- template.json
- contribute.html
  Other files still in en-US

@Synochy feel free to correct me ;) and to update other texts
I will check latest tomorrow morning to finish what will be left (more or less between 8 and 9 french time)

**Comment by DarkAngelFR-zz** [comment]
@Synochy : I added small comments on about PR, maybe we can find a better way to define what's this PoGoUWP in french ^^ (hard to find)

**Comment by josecfreittas** [comment]
Some changes have been made, now it's all done in markdown, not html. Now it is easy to edit direct by GitHub.

// I have already "translated" to markdown all you both had been submitted.

**Comment by DarkAngelFR-zz** [comment]
@Synochy : je viens de faire le merge :)
Merci pour le coup de main ^^

**Comment by Synochy** [comment]
@DarkAngelFR De rien !
Si tu as besoin hésite pas ;)
