### ISSUE TITLE
Translation DE

### ISSUE THREAD

**Issue by swisszeni** [PoGo-Devs/pogo-devs.github.io#5]
@PoGo-Devs/translators
### Tasks

Translate to German:
- [x] about
- [x] contribute
- [x] footer
- [x] instructions
- [x] template
### Responsible

Me
### Ref
#3

**Comment by FloMoTionGo** [comment]
Whats the status? Can I help translate the missing parts? ofc I dont want to do work twice, thats why I am asking ;)

**Comment by mKay00** [comment]
I just started. About is finished and now I'm working on contribute.

**Comment by FloMoTionGo** [comment]
So I ll start from the bottom of the list then.

**Comment by swisszeni** [comment]
Sorry, I'm very busy at work ATM, won't be until quite a bit later till I can participate/update.

**Comment by FloMoTionGo** [comment]
template.json done now instructions.html

the instruction itself is quite confusing: Whats "Device Portal"? Havent done it that way myself, when I installed the latest version. Should I change the instructions or just translate as is? 

Edit: I now see whats meant with "Device Portal" ... We are expecting a lot knowledge of future users to find this option in the options menu on w10mobile ;)

**Comment by DarkAngelFR-zz** [comment]
not related to DE but I've been doing kind of tutorial by mail for a friend (non IT), I may take some time this weekend to push it here (screenshots and so on)

**Comment by FloMoTionGo** [comment]
@DarkAngelFR I described the navigation to Device Portal and added that to the german instructions, but if you have an "official" one go ahead and post it we ll translate it then.

**Comment by FloMoTionGo** [comment]
please update the list. The website is already translated and besides some minor mistakes it is all done and already uploaded

**Comment by josecfreittas** [comment]
Thanks to anyone who helped. The translation has been done, so I'll close the issue.
